<?php

namespace Proxies\__CG__\CandidatBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Candidat extends \CandidatBundle\Entity\Candidat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'id', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'nomCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'prenomCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'dnCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'genre', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'ecCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'photoCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'adrCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'telCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'emailCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'titreCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'specialiteCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'netudeCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'expCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'compCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'descCam', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'cvCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'etatCan'];
        }

        return ['__isInitialized__', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'id', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'nomCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'prenomCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'dnCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'genre', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'ecCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'photoCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'adrCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'telCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'emailCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'titreCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'specialiteCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'netudeCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'expCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'compCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'descCam', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'cvCan', '' . "\0" . 'CandidatBundle\\Entity\\Candidat' . "\0" . 'etatCan'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Candidat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomCan($nomCan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomCan', [$nomCan]);

        return parent::setNomCan($nomCan);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomCan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomCan', []);

        return parent::getNomCan();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomCan($prenomCan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomCan', [$prenomCan]);

        return parent::setPrenomCan($prenomCan);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomCan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomCan', []);

        return parent::getPrenomCan();
    }

    /**
     * {@inheritDoc}
     */
    public function setDnCan($dnCan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDnCan', [$dnCan]);

        return parent::setDnCan($dnCan);
    }

    /**
     * {@inheritDoc}
     */
    public function getDnCan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDnCan', []);

        return parent::getDnCan();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenre($genre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenre', [$genre]);

        return parent::setGenre($genre);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenre', []);

        return parent::getGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function setEcCan($ecCan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEcCan', [$ecCan]);

        return parent::setEcCan($ecCan);
    }

    /**
     * {@inheritDoc}
     */
    public function getEcCan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEcCan', []);

        return parent::getEcCan();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotoCan($photoCan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoCan', [$photoCan]);

        return parent::setPhotoCan($photoCan);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoCan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoCan', []);

        return parent::getPhotoCan();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdrCan($adrCan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdrCan', [$adrCan]);

        return parent::setAdrCan($adrCan);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdrCan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdrCan', []);

        return parent::getAdrCan();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelCan($telCan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelCan', [$telCan]);

        return parent::setTelCan($telCan);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelCan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelCan', []);

        return parent::getTelCan();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailCan($emailCan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailCan', [$emailCan]);

        return parent::setEmailCan($emailCan);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailCan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailCan', []);

        return parent::getEmailCan();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreCan($titreCan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreCan', [$titreCan]);

        return parent::setTitreCan($titreCan);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreCan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreCan', []);

        return parent::getTitreCan();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecialiteCan($specialiteCan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecialiteCan', [$specialiteCan]);

        return parent::setSpecialiteCan($specialiteCan);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecialiteCan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecialiteCan', []);

        return parent::getSpecialiteCan();
    }

    /**
     * {@inheritDoc}
     */
    public function setNetudeCan($netudeCan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNetudeCan', [$netudeCan]);

        return parent::setNetudeCan($netudeCan);
    }

    /**
     * {@inheritDoc}
     */
    public function getNetudeCan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetudeCan', []);

        return parent::getNetudeCan();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpCan($expCan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpCan', [$expCan]);

        return parent::setExpCan($expCan);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpCan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpCan', []);

        return parent::getExpCan();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompCan($compCan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompCan', [$compCan]);

        return parent::setCompCan($compCan);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompCan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompCan', []);

        return parent::getCompCan();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescCam($descCam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescCam', [$descCam]);

        return parent::setDescCam($descCam);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescCam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescCam', []);

        return parent::getDescCam();
    }

    /**
     * {@inheritDoc}
     */
    public function setCvCan($cvCan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCvCan', [$cvCan]);

        return parent::setCvCan($cvCan);
    }

    /**
     * {@inheritDoc}
     */
    public function getCvCan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCvCan', []);

        return parent::getCvCan();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatCan($etatCan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatCan', [$etatCan]);

        return parent::setEtatCan($etatCan);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatCan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatCan', []);

        return parent::getEtatCan();
    }

}
